name: state_illustrator
description: "A Flutter package for creating and visualizing custom state illustrations."
version: 2.0.0
homepage: https://github.com/ASHISH1317/state_illustrator
repository: https://github.com/ASHISH1317/state_illustrator
issue_tracker: https://github.com/ASHISH1317/state_illustrator/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default/loading.json
    - assets/default/empty.svg
    - assets/default/error.png
